### ISSUE TITLE
iOS version requirement?

### ISSUE THREAD

**Issue by aaronhedquist** [nschum/SwiftCGRectExtensions#4]
Hi,

I wanted to try this out, but your podspec has a requirement of iOS 8, but your readme has iOS 6+. Does it really require 8.0?

Thanks

**Comment by nschum** [comment]
Sorry for the late answer.
CocoaPods requires using frameworks for Swift libraries and frameworks are only available on iOS 8 or later. Nothing in the code requires iOS 8.
